version: '3.7'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
  api:
    build:
      context: ./REST-API
    volumes:
      - ./REST-API:/app
    ports:
      - 5000:5000
volumes:
  notused: