name: Image Publication
on:
  push:
    branches:
      - master

jobs:
  publish-images:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Publish Docker Client Image
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: nvisal1/rate-my-salary-client
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./client/Dockerfile
    - name: Publish Docker Prediction Service Image
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: nvisal1/rate-my-salary-prediction-service
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./REST-API/Dockerfile